dist: trusty
sudo: false
language: go
go:
- 1.9

install:
  # This script is used by the Travis build to install a cookie for
  # go.googlesource.com so rate limits are higher when using `go get` to fetch
  # packages that live there.
  # See: https://github.com/golang/go/issues/12933
  - bash scripts/gogetcookie.sh
  - go get github.com/kardianos/govendor
  
env:
  - CGO_ENABLED=0

script:
  - make test
  - make vendor-status
  - make vet
  - make errcheck

before_deploy:
  - make packages

deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  file:
    - build/terraform-provider-helm_${TRAVIS_TAG}_darwin_amd64.tar.gz
    - build/terraform-provider-helm_${TRAVIS_TAG}_linux_amd64.tar.gz
  skip_cleanup: true
  on:
    tags: true
