name: "tests"
on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

jobs:
  unit_test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Unit tests
      env:
        GOPATH: /home/runner/go
      run: |
        make test
        make vet
  acc_test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        terraform_version: 
        - "0.12.30"
        - "0.13.6"
        - "0.14.4"
        - "0.15.0-alpha20210107"
    steps:
    - uses: actions/checkout@master
    - uses: engineerd/setup-kind@v0.5.0  
    - name: Acceptance Tests
      env: 
        TF_ACC_TERRAFORM_VERSION: ${{ matrix.terraform_version }}
      run: |
        KUBE_CONFIG_PATH="${HOME}/.kube/config" make testacc 
